# Generated by Django 2.1.7 on 2019-02-15 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('profilePicture', models.ImageField(upload_to='profiles/')),
                ('contactNo', models.CharField(max_length=13)),
                ('cprn', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('branch', models.CharField(max_length=30)),
                ('academicYear', models.CharField(max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('hasRating', models.BooleanField(default=False)),
                ('reviewsCount', models.PositiveIntegerField(default=0)),
                ('authAccount', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
