# Generated by Django 2.1.7 on 2019-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
    ]
