# Generated by Django 2.1.7 on 2019-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190215_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='operations.Category'),
            preserve_default=False,
        ),
    ]
