# Generated by Django 2.1.7 on 2019-02-15 12:40

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('operations', '0002_auto_20190215_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sell', models.BooleanField(default=True)),
                ('sellingPrice', models.PositiveIntegerField(default=0)),
                ('lendingPrice', models.PositiveIntegerField(default=0)),
                ('validity', models.PositiveIntegerField(default=1, help_text='Validity in Months')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('available', models.BooleanField(default=True)),
                ('reportedCount', models.PositiveIntegerField(default=0)),
                ('spam', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
