# Generated by Django 2.1.7 on 2019-02-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default=2, upload_to='products/'),
            preserve_default=False,
        ),
    ]
