# Generated by Django 2.1.7 on 2019-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190215_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='operations.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='default.jpeg', upload_to='products/'),
        ),
    ]
