# Generated by Django 2.0.13 on 2019-02-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20190215_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='buyerContact',
            field=models.CharField(default='+91704080608', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='buyerEmail',
            field=models.CharField(default='admin@lenditup.com', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='operations.Category'),
        ),
    ]
