# Generated by Django 2.0.13 on 2019-02-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_email'),
        ('operations', '0006_auto_20190216_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=2, on_delete='CASCADE', to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, default='NA', max_length=100),
        ),
    ]
